# Stage 1: Build the react app
FROM node:14 as builder

WORKDIR /app/frontend

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve the app using a lightweight node server
FROM node:14

WORKDIR /app

# Install serve globally
RUN npm install -g serve

# Copy build folder from builder stage
COPY --from=builder /app/frontend/build /app/build

CMD ["serve", "-s", "/app/build", "-l", "3000"]
