version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment: {}
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app/frontend
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment: {}
    env_file:
      - ./.env

  mongo:
    image: mongo:4.4
    container_name: app-db
    networks:
      - app-network
    volumes:
      - db-mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:

volumes:
  db-mongo:

